1 v.0.1.1
3xMike/config-manager pull request #2
Opened 2023-03-06 07:25 UTC by 3xMike

2023-03-08 19:28 UTC, memoryallocator requested changes

2023-03-08 19:28 UTC, memoryallocator commented on CHANGELOG.md
> +- The default behavior of `env_prefix` is no prefix instead of a binary name now
```suggestion
- The default behavior of `env_prefix` is now prefix instead of a binary name now
```

2023-03-08 19:28 UTC, memoryallocator commented on config-manager-proc/src/utils/config.rs
> +        _ => panic!("{} format is not supported", s),
```suggestion
        _ => panic!("{s} format is not supported"),
```

2023-03-08 19:28 UTC, memoryallocator commented on config-manager-proc/src/utils/field.rs
> +            ..std::default::Default::default()
```suggestion
                FieldAttribute::Clap(Default::default()),
                FieldAttribute::Env(Default::default()),
                FieldAttribute::Config(Default::default()),
            ],
            ..Default::default()
```

2023-03-08 19:28 UTC, memoryallocator commented on config-manager-proc/src/utils/field/utils.rs
> +                                    panic!("source attribute ({:#?}) can't be a literal", lit)
```suggestion
                                    panic!("source attribute ({lit:#?}) can't be a literal")
```

2023-03-08 19:28 UTC, memoryallocator commented on cookbook.md
> +Prefix of the environment variables. If not stated, the prefix will not be added.
```suggestion
Prefix of the environment variables. If not specified, the prefix will not be added.
```

2023-03-08 19:28 UTC, memoryallocator commented on cookbook.md
> +- One can use `env_prefix` (without a value) to set the binary file name as a prefix
`env_prefix` (without a value) -- предлагаю добавить пример.

2023-03-08 19:28 UTC, memoryallocator commented on cookbook.md
> +If the attribute is set without a value (`#[source(default)]`), the default value is `std::default::Default`.
```suggestion
If the attribute is set without a value (`#[source(default)]`), the default value is `Default::default()`.
```
Я бы сказал, и так понятно, что речь об std.

2023-03-08 19:28 UTC, memoryallocator commented on src/__cookbook.rs
> +//! Prefix of the environment variables. If not stated, the prefix will not be added.
(см. выше)

2023-03-08 19:28 UTC, memoryallocator commented on src/__cookbook.rs
> +//! If the attribute is set without a value (`#[source(default)]`), the default value is `std::default::Default`.
(см. выше)

2023-03-09 08:54 UTC, 3xMike commented on CHANGELOG.md
> +- The default behavior of `env_prefix` is no prefix instead of a binary name now
?

2023-03-09 09:00 UTC, memoryallocator commented on CHANGELOG.md
> +- The default behavior of `env_prefix` is no prefix instead of a binary name now
Прошу прощения, не туда посмотрел. Давай напишем "empty prefix" вместо "no prefix".

2023-03-09 09:15 UTC, merged